apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ecommerce
  namespace: argocd
spec:
  # Repos this project can use
  sourceRepos:
    - 'https://github.com/himanshunigam-456/ecommerce-gitops.git'
    - 'https://github.com/himanshunigam-456/microservices-demo.git'

  # Where it is allowed to deploy
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

