apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecom-dev-online-boutique
  namespace: argocd
spec:
  project: ecommerce

  source:
    repoURL: https://github.com/himanshunigam-456/microservices-demo.git
    targetRevision: main          # or HEAD, both are fine
    path: kubernetes-manifests    # ✅ plain K8s manifests, no CRDs
                                  # (no "directory:" block needed)

  destination:
    server: https://kubernetes.default.svc
    namespace: ecom-dev

  syncPolicy:
    syncOptions:
      - CreateNamespace=true      # let Argo create ecom-dev if needed
    automated:
      prune: true
      selfHeal: true
