apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecom-prod-online-boutique
  namespace: argocd
spec:
  project: ecommerce
  source:
    repoURL: 'https://github.com/himanshunigam-456/microservices-demo.git'
    targetRevision: HEAD
    path: kubernetes-manifests      # 🔴 change here too
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ecom-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

