apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecom-dev-online-boutique
  namespace: argocd
spec:
  project: ecommerce
  source:
    repoURL: 'https://github.com/himanshunigam-456/microservices-demo.git'
    targetRevision: main
    path: release
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: ecom-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
